project_id = "flqwpuixevufwxfktdxg"

[functions.stripe-payment]
verify_jwt = false

[functions.sslcommerz-payment]
verify_jwt = false

[functions.bkash-payment]
verify_jwt = false

[functions.payment-webhook]
verify_jwt = false

[functions.subscription-email]
verify_jwt = false

[functions.renewal-reminder]
verify_jwt = false

[functions.project-ai]
verify_jwt = false

[functions.health-analysis]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.agro-analysis]
verify_jwt = false
