import React, { useState } from "react";
import {
  FileText,
  ChevronRight,
  Shield,
  Scale,
  AlertCircle,
  CheckCircle,
  ExternalLink,
  Calendar,
  BookOpen,
} from "lucide-react";
import { cn } from "@/lib/utils";

const TERMS_SECTIONS = [
  {
    id: "acceptance",
    icon: CheckCircle,
    title: "Acceptance of Terms",
    content: `By accessing or using AI Sorix ("the Service"), you agree to be bound by these Terms of Use. If you do not agree to all terms and conditions, you may not use the Service.

These terms apply to all users, including visitors, registered users, and contributors. Your continued use of the Service constitutes acceptance of any updates to these terms.`,
  },
  {
    id: "services",
    icon: BookOpen,
    title: "Description of Services",
    content: `AI Sorix provides AI-powered conversational services, including but not limited to:

• Natural language processing and generation
• Multi-model AI chat capabilities  
• Conversation export and sharing features
• Premium subscription services

We reserve the right to modify, suspend, or discontinue any aspect of the Service at any time without prior notice.`,
  },
  {
    id: "user-conduct",
    icon: Scale,
    title: "User Conduct",
    content: `You agree to use the Service responsibly and legally. Prohibited activities include:

• Attempting to gain unauthorized access to any systems
• Using the Service for illegal or harmful purposes
• Generating content that violates laws or rights of others
• Interfering with or disrupting the Service
• Impersonating any person or entity
• Transmitting malware or harmful code

We reserve the right to terminate accounts that violate these guidelines.`,
  },
  {
    id: "intellectual-property",
    icon: Shield,
    title: "Intellectual Property",
    content: `All content, features, and functionality of AI Sorix are owned by us and protected by international copyright, trademark, and other intellectual property laws.

Your Content: You retain ownership of content you create. By using the Service, you grant us a license to process your content to provide the Service.

AI-Generated Content: Output generated by AI models may be used by you subject to these terms, but we make no claims of originality or exclusivity.`,
  },
  {
    id: "privacy",
    icon: Shield,
    title: "Privacy & Data",
    content: `Your privacy is important to us. Our use and collection of personal information is governed by our Privacy Policy.

Key points:
• We collect only necessary data to provide the Service
• Your conversations are encrypted and secure
• We do not sell your personal information
• You can request deletion of your data at any time

For complete details, please review our Privacy Policy.`,
  },
  {
    id: "liability",
    icon: AlertCircle,
    title: "Limitation of Liability",
    content: `AI Sorix is provided "as is" without warranties of any kind. We do not guarantee:

• Uninterrupted or error-free service
• Accuracy or reliability of AI-generated content
• Suitability for any particular purpose

To the maximum extent permitted by law, we shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service.`,
  },
  {
    id: "termination",
    icon: AlertCircle,
    title: "Termination",
    content: `We may terminate or suspend your access immediately, without prior notice, for any reason, including breach of these Terms.

Upon termination:
• Your right to use the Service will cease immediately
• You may export your data before account closure
• Provisions that by nature should survive will remain in effect`,
  },
  {
    id: "changes",
    icon: FileText,
    title: "Changes to Terms",
    content: `We reserve the right to modify these terms at any time. We will notify users of significant changes via:

• Email notification to registered users
• Prominent notice on our website
• In-app notifications

Your continued use after changes constitutes acceptance of the new terms.`,
  },
];

const TermsTab = () => {
  const [expandedSection, setExpandedSection] = useState<string | null>("acceptance");

  const lastUpdated = "January 15, 2025";

  return (
    <div className="h-full flex flex-col">
      <div className="mb-4 sm:mb-6">
        <div className="flex items-center gap-2 sm:gap-3 mb-2">
          <div className="w-8 h-8 sm:w-10 sm:h-10 rounded-lg sm:rounded-xl bg-gradient-to-br from-violet-500 to-purple-600 flex items-center justify-center">
            <FileText className="w-4 h-4 sm:w-5 sm:h-5 text-white" />
          </div>
          <div>
            <h3 className="text-lg sm:text-xl font-bold">Terms of Use</h3>
            <p className="text-xs sm:text-sm text-muted-foreground">Please read these terms carefully</p>
          </div>
        </div>

        <div
          className={cn("inline-flex items-center gap-2 px-3 py-1.5 rounded-lg mt-3", "bg-muted border border-border")}
        >
          <Calendar className="w-3.5 h-3.5 text-muted-foreground" />
          <span className="text-xs text-muted-foreground">
            Last updated: <span className="text-foreground font-medium">{lastUpdated}</span>
          </span>
        </div>
      </div>

      <div
        className={cn(
          "p-4 rounded-xl mb-4 sm:mb-5",
          "bg-gradient-to-br from-primary/5 to-accent/5 border border-primary/20",
        )}
      >
        <p className="text-sm text-muted-foreground leading-relaxed">
          Welcome to AI Sorix. These Terms of Use govern your access to and use of our services. By using AI Sorix, you
          agree to these terms. Please review them carefully.
        </p>
      </div>

      <div className="flex-1 overflow-y-auto pr-1 sm:pr-2 space-y-2">
        {TERMS_SECTIONS.map((section) => {
          const Icon = section.icon;
          const isExpanded = expandedSection === section.id;

          return (
            <div
              key={section.id}
              className={cn(
                "border rounded-xl overflow-hidden transition-all duration-200",
                isExpanded ? "bg-card border-primary/30" : "bg-card border-border hover:border-primary/20",
              )}
            >
              <button
                onClick={() => setExpandedSection(isExpanded ? null : section.id)}
                className="w-full flex items-center gap-3 p-3 sm:p-4 text-left"
              >
                <div
                  className={cn(
                    "w-8 h-8 rounded-lg flex items-center justify-center flex-shrink-0 transition-colors",
                    isExpanded ? "bg-primary/10" : "bg-muted",
                  )}
                >
                  <Icon
                    className={cn("w-4 h-4 transition-colors", isExpanded ? "text-primary" : "text-muted-foreground")}
                  />
                </div>
                <span
                  className={cn(
                    "flex-1 text-sm font-medium transition-colors",
                    isExpanded ? "text-primary" : "text-foreground",
                  )}
                >
                  {section.title}
                </span>
                <ChevronRight
                  className={cn(
                    "w-4 h-4 text-muted-foreground transition-transform duration-200 flex-shrink-0",
                    isExpanded && "rotate-90",
                  )}
                />
              </button>

              {isExpanded && (
                <div className="px-3 sm:px-4 pb-4 pt-0">
                  <div className="pl-11">
                    <p className="text-sm text-muted-foreground leading-relaxed whitespace-pre-line">
                      {section.content}
                    </p>
                  </div>
                </div>
              )}
            </div>
          );
        })}
      </div>

      <div className={cn("p-4 rounded-xl mb-4", "bg-muted/50 border border-border")}>
        <p className="text-xs text-muted-foreground">
          Have questions about these terms? Contact us at{" "}
          <a href="mailto:support@aisorix.com" className="text-primary hover:underline font-medium">
            support@aisorix.com
          </a>
        </p>
      </div>

      <div className="pt-4 sm:pt-5 mt-auto border-t border-border">
        <div className="flex flex-col sm:flex-row gap-2 sm:gap-3">
          <button
            onClick={() => window.open("https://www.aisorix.com/terms-of-service", "_blank")}
            className={cn(
              "flex-1 py-2.5 sm:py-3 rounded-xl font-medium text-sm transition-all duration-200",
              "flex items-center justify-center gap-2",
              "bg-primary text-primary-foreground hover:shadow-glow",
            )}
          >
            <ExternalLink className="w-4 h-4" />
            View Full Terms
          </button>
          <button
            onClick={() => window.open("https://www.aisorix.com/privacy-policy", "_blank")}
            className={cn(
              "flex-1 py-2.5 sm:py-3 rounded-xl font-medium text-sm transition-all duration-200",
              "flex items-center justify-center gap-2",
              "bg-muted text-foreground hover:bg-accent border border-border",
            )}
          >
            <Shield className="w-4 h-4" />
            Privacy Policy
          </button>
        </div>
      </div>
    </div>
  );
};

export default TermsTab;
